apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bar
  name: bar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bar
    spec:
      containers:
      - image: hashicorp/http-echo:0.2.3
        name: http-echo
        args:
        - "-text=<h1>Hello bar app</h1>"
        resources: {}
status: {}
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bar-ingress
spec:
  rules:
  # Replace ip with your public one
  # To find your public IP run command : sh my-public-ip.sh
  - host: bar.34.121.248.140.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bar-service
            port:
              number: 5678
